# Generated by Django 5.2 on 2025-07-22 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='created',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='idvendeur',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='updated',
        ),
        migrations.AddField(
            model_name='annonce',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='web_app.vendeur'),
        ),
    ]
